version: '3.7'

services:
  backend: &backend
    build: .
    image: elixir_formula_app
    depends_on:
      - postgres
      - redis
    env_file:
      - .env.development
    stdin_open: true
    tty: true
    volumes:
      - .:/elixir_formula:cached
      - bundle:/usr/local/bundle
      - rails_cache:/app/tmp/cache
    tmpfs:
      - /tmp

  app:
    <<: *backend
    container_name: application
    ports:
      - 3000:3000
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"

  sidekiq:
    <<: *backend
    container_name: sidekiq
    command: bundle exec sidekiq -C config/sidekiq.yml

  postgres:
    image: postgres:11.1
    container_name: postgres
    ports:
      - 5432
    env_file:
      - .env.development
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:3.2.5
    container_name: redis
    ports:
      - 6379
    healthcheck:
      test: "exit 0"
    volumes:
      - redis:/var/lib/redis/data

volumes:
  bundle:
  db_data: {}
  redis:
  rails_cache:
